updates:
  - directory: "/"
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
version: 2
